language: node_js

node_js:
    - "0.10"

before_install:
    - npm install -g grunt-cli bower

before_script:
    - npm install karma-phantomjs-launcher
    - bower install --force-latest 

after_success:
    - grunt coveralls

sudo: false
