mongodb:
  image: mongo:3
  container_name: mongodb

redis:
  image: redis:3
  container_name: redis

elastic:
  image: elasticsearch:2
  container_name: elastic

postfix:
  image: catatnight/postfix
  container_name: postfix
  environment:
  - maildomain=mail.sourcefabric.org
  - smtp_user=user:pwd

grammalecte:
  build: grammalecte/
  container_name: grammalecte

superdesk:
  build: ../
  container_name: superdesk
  environment:
   - SUPERDESK_URL=http://127.0.0.1/api
   - SUPERDESK_WS_URL=ws://127.0.0.1/ws
   - SUPERDESK_CLIENT_URL=http://127.0.0.1
   - GRAMMALECTE_URL=http://grammalecte:9999
   - MONGO_URI=mongodb://mongodb/test
   - PUBLICAPI_MONGO_URI=mongodb://mongodb/test_pa
   - LEGAL_ARCHIVE_URI=mongodb://mongodb/test_la
   - ARCHIVED_URI=mongodb://mongodb/test_ar
   - ELASTICSEARCH_URL=http://elastic:9200
   - ELASTICSEARCH_INDEX=superdesk
   - CELERY_BROKER_URL=redis://redis:6379/1
   - REDIS_URL=redis://redis:6379/1
   - LOG_SERVER_ADDRESS=logstash
   - LOG_SERVER_PORT=5555
   - AMAZON_ACCESS_KEY_ID
   - AMAZON_CONTAINER_NAME
   - AMAZON_REGION
   - AMAZON_SECRET_ACCESS_KEY
   - REUTERS_USERNAME
   - REUTERS_PASSWORD
   - MAIL_SERVER=postfix
   - MAIL_PORT=25
   - MAIL_USE_TLS=false
   - MAIL_USE_SSL=false
   - MAIL_USERNAME=user
   - MAIL_PASSWORD=pwd
   - SENTRY_DSN
   - VIEW_DATE_FORMAT
   - VIEW_TIME_FORMAT
   - SECRET_KEY
