mongodb:
  image: mongo:2.6
  volumes:
   - ../data/mongodb:/data/db

redis:
  image: redis:2.8
  volumes:
   - ../data/redis:/data

logstash:
  image: logstash
  command: logstash -f /usr/share/logstash/logstash.conf
  volumes:
  - logstash:/usr/share/logstash

kibana:
  build: kibana
  restart: always
  ports:
  - "5601:5601"

elastic:
  image: elasticsearch:1.5
  volumes:
   - ../data/elastic:/usr/share/elasticsearch/data

postfix:
  image: catatnight/postfix
  environment:
  - maildomain=mail.sourcefabric.org
  - smtp_user=user:pwd

backend:
  build: ../server
  command: sh /opt/superdesk/scripts/fig_wrapper.sh honcho start
  environment:
   - MONGO_URI=mongodb://mongodb/test
   - PUBLICAPI_MONGO_URI=mongodb://mongodb/test
   - LEGAL_ARCHIVE_URI=mongodb://mongodb/test
   - ELASTICSEARCH_URL=http://elastic:9200
   - ELASTICSEARCH_INDEX
   - CELERY_BROKER_URL=redis://redis:6379/1
   - REDIS_URL=redis://redis:6379/1
   - LOG_SERVER_ADDRESS=logstash
   - LOG_SERVER_PORT=5555
   - AMAZON_ACCESS_KEY_ID
   - AMAZON_CONTAINER_NAME
   - AMAZON_REGION
   - AMAZON_SECRET_ACCESS_KEY
   - REUTERS_USERNAME
   - REUTERS_PASSWORD
   - MAIL_SERVER=postfix
   - MAIL_PORT=25
   - MAIL_USE_TLS=false
   - MAIL_USE_SSL=false
   - MAIL_USERNAME=user
   - MAIL_PASSWORD=pwd
   - SENTRY_DSN
   - SUPERDESK_URL=http://127.0.0.1/api
   - SUPERDESK_CLIENT_URL=http://127.0.0.1
   - SUPERDESK_TESTING=True
  volumes:
   - ../results/server/unit:/opt/superdesk/results-unit/
   - ../results/server/behave:/opt/superdesk/results-behave/

frontend:
  build: ../client
  command: sh -c "grunt build --server='http://127.0.0.1/api' --ws='ws://127.0.0.1/ws' && nginx"
  volumes:
   - ../results/client/unit:/opt/superdesk-client/unit-test-results
  ports:
   - "443:443"
   - "80:80"
